site_name: radCAD documentation


theme:
  name: "material"


plugins:
  - mkdocstrings

markdown_extensions:
    - toc:
        permalink: "#"


nav:
  - Overview: index.md
  - Getting started: gettingstarted.md
  - Examples:
    - Examples: examples.md
    - Examples (accessible): examples_accessible.md
  - Features:
    - Features: features.md
    - Advanced Features: advanced_features.md
  - Reference: 
     - Reference: reference.md
     - Development: development.md
     - cadCAD Compatibility: cadcad_compatibility.md
     - Model Architecture: model_architecture.md
  - About: about.md