# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build Status

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        python-major-version: [3]
        python-minor-version: [8, 9, 10, 11, 12]
        os: [ubuntu, windows, macOS]
    env:
      python-version: ${{ format('{0}.{1}', matrix.python-major-version, matrix.python-minor-version) }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.python-version }}
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install pdm nox
    - name: Install build dependencies for MacOS
      if: ${{ matrix.os == 'macOS' }}
      run: |
        brew install hdf5 c-blosc
    - name: Install radCAD dependencies for Python 3.8
      if: ${{ matrix.python-minor-version == 8 }}
      run: |
        pdm sync -d -G compat --lockfile pdm-py38.lock
    - name: Install radCAD dependencies for Python 3.9+
      if: ${{ matrix.python-minor-version >= 9 }}
      run: |
        pdm sync -d -G compat --lockfile pdm.lock
    - name: Run tests using Nox
      run: |
        python -m nox -s tests-${{ env.python-version }}
